name: "Flarum Build"
author: "Kitsune Solar <kitsune.solar@gmail.com>"
description: ""
branding:
  icon: ""
  color: ""
inputs:
  source:
    description: "Source"
    required: true
  target:
    description: "Target"
    required: true
  username:
    description: "Username"
    required: true
  email:
    description: "E-mail"
    required: true
  token:
    description: "Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source }}
    - ${{ inputs.target }}
    - ${{ inputs.username }}
    - ${{ inputs.email }}
    - ${{ inputs.token }}
